

# This file was *autogenerated* from the file ./crelle_isom_weak_psdmdf.sage
from sage.all_cmdline import *   # import sage library

_sage_const_10 = Integer(10); _sage_const_6 = Integer(6); _sage_const_1 = Integer(1); _sage_const_30 = Integer(30); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0)
import json
from tqdm import tqdm
m=_sage_const_10 
n=_sage_const_6 


def read_file(filename):
    with open(filename, 'rb') as f:
        data = f.readlines()
    data = [x.strip() for x in data]
    return data


def text(result,path):
    t = open(path, mode='a', encoding='utf-8')
    for K in result:
        t.write(str(K) + '\n')
    t.close()


list_2_pow = [_sage_const_1 ]
for k in range(_sage_const_30 ):
    list_2_pow.append(list_2_pow[-_sage_const_1 ] * _sage_const_2 )

def face_to_binary(face, m):
    binary_face = m * [_sage_const_0 ]
    for k in face:
        binary_face[m - k] = _sage_const_1 
    return int(''.join(map(str, binary_face)), _sage_const_2 )

def binary_to_face(x, m):
    return [k + _sage_const_1  for k in range(m) if (list_2_pow[k] | x) == x]

raw_results_path = 'results_crelle/seed_weak_psdmfd_%d_%d' % (m,n)
results = [json.loads(facets_bytes) for facets_bytes in read_file(raw_results_path)]
N=len(results)
print("imported")
isom_weak_psdmfd = []
for facets_bin in tqdm(results):
    facets = [binary_to_face(facet_bin,m) for facet_bin in facets_bin]
    K1 = SimplicialComplex(facets)
    # K1_MNF = SimplicialComplex(K1.minimal_nonfaces())
    is_isom = False
    for K2 in isom_weak_psdmfd:
        #K2_MNF = SimplicialComplex(K1.minimal_nonfaces())
        if K2.is_isomorphic(K1):
            is_isom=True
            break
    if not is_isom:
        isom_weak_psdmfd.append(K1)
    else:
        del K1
print("third row: ",len(isom_weak_psdmfd))
Crelle_result_path = 'results_Crelle/seed_weak_psdmfd_isom_%d_%d' % (m,n)
text([face_to_binary([list(facet) for facet in K.facets()],m) for K in isom_weak_psdmfd],Crelle_result_path)





